import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import FacilityProvider from "@/providers/FacilityProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <FacilityProvider
              facilities={[]}
              initialActiveFacilityId=""
              currentUser={{
                id: "",
                email: null,
                firstName: "",
                lastName: "",
                role: "GUEST",
              }}
            >
              {children}
            </FacilityProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
